name: IdzCar Dream Route

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          envkey_REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          envkey_REACT_APP_API_TOKEN: ${{ secrets.REACT_APP_API_TOKEN }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build app
        run: npm run build
        env:
          CI: ""

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Purge cache
      #   uses: nathanvaughn/actions-cloudflare-purge@master
      #   with:
          # Zone is required by both authentication methods
          # cf_zone: ${{ secrets.CLOUDFLARE_ZONE }} 
          # cf_auth: ${{ secrets.CLOUDFLARE_KEY }}